backend:
  bucket: flipside-crypto-internal-tooling
  region: us-east-1
  dynamodb_table: internal-tooling-terraform-state
  encrypt: true
workspaces:
  terraform-aws-organization/components/compass/containers/compass/policies/rpc-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/policies/rpc-prod
    state_key: terraform/state/compass/workspaces/containers/compass/policies/rpc-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/policies/rpc-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/policies/rpc-stg
    state_key: terraform/state/compass/workspaces/containers/compass/policies/rpc-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/policies/workers-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/policies/workers-prod
    state_key: terraform/state/compass/workspaces/containers/compass/policies/workers-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/policies/workers-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/policies/workers-stg
    state_key: terraform/state/compass/workspaces/containers/compass/policies/workers-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/system-resources/rpc-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/system-resources/rpc-prod
    state_key: terraform/state/compass/workspaces/containers/compass/system-resources/rpc-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/system-resources/rpc-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/system-resources/rpc-stg
    state_key: terraform/state/compass/workspaces/containers/compass/system-resources/rpc-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/system-resources/workers-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/system-resources/workers-prod
    state_key: terraform/state/compass/workspaces/containers/compass/system-resources/workers-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/system-resources/workers-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/system-resources/workers-stg
    state_key: terraform/state/compass/workspaces/containers/compass/system-resources/workers-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/tasks/rpc-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/tasks/rpc-prod
    state_key: terraform/state/compass/workspaces/containers/compass/tasks/rpc-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/tasks/rpc-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/tasks/rpc-stg
    state_key: terraform/state/compass/workspaces/containers/compass/tasks/rpc-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/tasks/workers-prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/tasks/workers-prod
    state_key: terraform/state/compass/workspaces/containers/compass/tasks/workers-prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/containers/compass/tasks/workers-stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/containers/compass/tasks/workers-stg
    state_key: terraform/state/compass/workspaces/containers/compass/tasks/workers-stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/database-monitoring/prod:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/database-monitoring/prod
    state_key: terraform/state/compass/workspaces/database-monitoring/prod/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/database-monitoring/stg:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/database-monitoring/stg
    state_key: terraform/state/compass/workspaces/database-monitoring/stg/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/components/compass/generator:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/generator
    state_key: terraform/state/compass/workspaces/generator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/components/compass/infrastructure:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/infrastructure
    state_key: terraform/state/compass/workspaces/infrastructure/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/components/compass/post-processing:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/compass/post-processing
    state_key: terraform/state/compass/workspaces/post-processing/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/components/rstudio/generator:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/rstudio/generator
    state_key: terraform/state/rstudio/workspaces/generator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/aggregator:
    hcl_path: terraform/workspaces/terraform-aws-organization/aggregator
    state_key: terraform/state/terraform-aws-organization/workspaces/aggregator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/authentication:
    hcl_path: terraform/workspaces/terraform-aws-organization/authentication
    state_key: terraform/state/terraform-aws-organization/workspaces/authentication/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/bots:
    hcl_path: terraform/workspaces/terraform-aws-organization/bots
    state_key: terraform/state/terraform-aws-organization/workspaces/bots/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/generator:
    hcl_path: terraform/workspaces/terraform-aws-organization/generator
    state_key: terraform/state/terraform-aws-organization/workspaces/generator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/guards:
    hcl_path: terraform/workspaces/terraform-aws-organization/guards
    state_key: terraform/state/terraform-aws-organization/workspaces/guards/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/organization:
    hcl_path: terraform/workspaces/terraform-aws-organization/organization
    state_key: terraform/state/terraform-aws-organization/workspaces/organization/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/secrets:
    hcl_path: terraform/workspaces/terraform-aws-organization/secrets
    state_key: terraform/state/terraform-aws-organization/workspaces/secrets/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/sso:
    hcl_path: terraform/workspaces/terraform-aws-organization/sso
    state_key: terraform/state/terraform-aws-organization/workspaces/sso/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/security/aggregator:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/aggregator
    state_key: terraform/state/terraform-aws-security/workspaces/aggregator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/security/config:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/config
    state_key: terraform/state/terraform-aws-security/workspaces/config/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-aws-organization/security/delegation:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/delegation
    state_key: terraform/state/terraform-aws-security/workspaces/delegation/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/security/guardduty:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/guardduty
    state_key: terraform/state/terraform-aws-security/workspaces/guardduty/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/security/macie:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/macie
    state_key: terraform/state/terraform-aws-security/workspaces/macie/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/security/securityhub:
    hcl_path: terraform/workspaces/terraform-aws-organization/security/securityhub
    state_key: terraform/state/terraform-aws-security/workspaces/securityhub/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: true
  terraform-aws-organization/components/datadog/generator:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/datadog/generator
    state_key: terraform/state/terraform-datadog-monitoring/workspaces/generator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
  terraform-google-organization/gcp/authentication:
    hcl_path: terraform/workspaces/terraform-google-organization/gcp/authentication
    state_key: terraform/state/terraform-google-organization/workspaces/gcp/authentication/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: true
  terraform-google-organization/gcp/functions:
    hcl_path: terraform/workspaces/terraform-google-organization/gcp/functions
    state_key: terraform/state/terraform-google-organization/workspaces/gcp/functions/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: false
  terraform-google-organization/gcp/policies:
    hcl_path: terraform/workspaces/terraform-google-organization/gcp/policies
    state_key: terraform/state/terraform-google-organization/workspaces/gcp/policies/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: true
  terraform-google-organization/gcp/projects:
    hcl_path: terraform/workspaces/terraform-google-organization/gcp/projects
    state_key: terraform/state/terraform-google-organization/workspaces/gcp/projects/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: true
  terraform-google-organization/generator:
    hcl_path: terraform/workspaces/terraform-google-organization/generator
    state_key: terraform/state/terraform-google-organization/workspaces/generator/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: true
  terraform-google-organization/gws/assignments:
    hcl_path: terraform/workspaces/terraform-google-organization/gws/assignments
    state_key: terraform/state/terraform-google-organization/workspaces/gws/assignments/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: true
  terraform-google-organization/gws/org_units:
    hcl_path: terraform/workspaces/terraform-google-organization/gws/org_units
    state_key: terraform/state/terraform-google-organization/workspaces/gws/org_units/terraform.tfstate
    pipeline: terraform-google-organization
    has_main_tf: false
  terraform-aws-organization/components/fireblocks/generator:
    hcl_path: terraform/workspaces/terraform-aws-organization/components/fireblocks/generator
    state_key: terraform/state/terraform-treasury/workspaces/generator/terraform.tfstate
    pipeline: terraform-aws-organization
    has_main_tf: false
