groups:
  analytics@flipsidecrypto.com:
    members:
      austin@flipsidecrypto.com:
        role: MANAGER
        type: USER
      desmond@flipsidecrypto.com:
        role: MEMBER
        type: USER
      eric.laurello@flipsidecrypto.com:
        role: MANAGER
        type: USER
      graham@flipsidecrypto.com:
        role: MEMBER
        type: USER
      jack.forgash@flipsidecrypto.com:
        role: MEMBER
        type: USER
      james@flipsidecrypto.com:
        role: MANAGER
        type: USER
      jensen.yap@flipsidecrypto.com:
        role: MEMBER
        type: USER
      joan@flipsidecrypto.com:
        role: MEMBER
        type: USER
      liz@flipsidecrypto.com:
        role: MANAGER
        type: USER
      mattromano@flipsidecrypto.com:
        role: MEMBER
        type: USER
      mike.stepanovic@flipsidecrypto.com:
        role: MEMBER
        type: USER
      sam@flipsidecrypto.com:
        role: MEMBER
        type: USER
      shah@flipsidecrypto.com:
        role: MEMBER
        type: USER
      stanley@flipsidecrypto.com:
        role: MEMBER
        type: USER
      tarik@flipsidecrypto.com:
        role: MEMBER
        type: USER
      trevor@flipsidecrypto.com:
        role: MEMBER
        type: USER
  analytics_requests@flipsidecrypto.com:
    email: analytics-requests@flipsidecrypto.com
    members:
      james@flipsidecrypto.com:
        role: OWNER
        type: USER
  applemanager@flipsidecrypto.com:
    members:
      jon@flipsidecrypto.com:
        role: OWNER
        type: USER
  billing@flipsidecrypto.com:
    members:
      finops@flipsidecrypto.com:
        role: OWNER
        type: GROUP
      jon@flipsidecrypto.com:
        role: MEMBER
        type: USER
      salma.adan@flipsidecrypto.com:
        role: MEMBER
        type: USER
  blockchain_admins@flipsidecrypto.com:
    email: blockchain-admins@flipsidecrypto.com
    members:
      greg@flipsidecrypto.com:
        role: MEMBER
        type: USER
      ryan.king@flipsidecrypto.com:
        role: OWNER
        type: USER
  finops@flipsidecrypto.com:
    members:
      liron@flipsidecrypto.com:
        role: MANAGER
        type: USER
      mike.featherstone@flipsidecrypto.com:
        role: OWNER
        type: USER
      nick.fulton@flipsidecrypto.com:
        role: MEMBER
        type: USER
  invoices@flipsidecrypto.com:
    members:
      finops@flipsidecrypto.com:
        role: OWNER
        type: GROUP
      salma.adan@flipsidecrypto.com:
        role: MEMBER
        type: USER
  receipts@flipsidecrypto.com:
    members:
      finops@flipsidecrypto.com:
        role: OWNER
        type: GROUP
  taxforms@flipsidecrypto.com:
    members:
      finops@flipsidecrypto.com:
        role: OWNER
        type: GROUP
  trading@flipsidecrypto.com:
    members:
      finops@flipsidecrypto.com:
        role: MANAGER
        type: GROUP
      jim@flipsidecrypto.com:
        role: OWNER
        type: USER
      salma.adan@flipsidecrypto.com:
        role: MEMBER
        type: USER
  gcp_billing_admins@flipsidecrypto.com:
    email: gcp-billing-admins@flipsidecrypto.com
    members:
      finops@flipsidecrypto.com:
        role: OWNER
        type: GROUP
  treasury@flipsidecrypto.com:
    members:
      greg@flipsidecrypto.com:
        role: OWNER
        type: USER
      paul@flipsidecrypto.com:
        role: MEMBER
        type: USER
      ryan.king@flipsidecrypto.com:
        role: MEMBER
        type: USER
      finops@flipsidecrypto.com:
        role: MANAGER
        type: GROUP
  eng-infra@flipsidecrypto.com:
    members:
      dan.shank@flipsidecrypto.com:
        role: OWNER
        type: USER
