flipsidecrypto:
  name: FlipsideCrypto
  description: Primary Flipside Crypto GCP Project
fsc_supabase_auth_external:
  name: FSCSupabaseAuthExternal
  project_id: fsc-supabase-auth-external
  description: GCP Project for External Supabase Authentication
fsc_supabase_auth_external_stg:
  name: FSCSupabaseAuthExternalStaging
  project_id: fsc-supabase-auth-external-stg
  description: GCP Project for External Supabase Authentication (Staging)