blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/jbdevprimary
    about: Check the docs before filing an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/jbdevprimary?tab=repositories
    about: Find repository-specific discussions in each project
