name: Test CI

on:
  push:
    branches: [fix/ci-unicode-characters]
  workflow_dispatch:

jobs:
  call-test:
    uses: jbcom/jbcom-control-center/.github/workflows/reusable/lint.yml@fix/ci-unicode-characters
