name: Test CI

on:
  push:
    branches: [fix/ci-unicode-characters]
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.set.outputs.test }}
    steps:
      - id: set
        run: echo "test=[\"a\",\"b\"]" >> $GITHUB_OUTPUT
  
  use-matrix:
    needs: matrix-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.matrix-job.outputs.test) }}
    steps:
      - run: echo "Item ${{ matrix.item }}"
